// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3YqnUEnRfts82fhjOleVPmKMvp3r74pY',
    appId: '1:158624427242:web:408a5c4d043745f35a3b93',
    messagingSenderId: '158624427242',
    projectId: 'business-management-app-112ea',
    authDomain: 'business-management-app-112ea.firebaseapp.com',
    storageBucket: 'business-management-app-112ea.firebasestorage.app',
    measurementId: 'G-QLGRSHNPTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABkwIWkfjdRloxPfTXKy_34JL2XqdM9dA',
    appId: '1:158624427242:android:615f99df287681315a3b93',
    messagingSenderId: '158624427242',
    projectId: 'business-management-app-112ea',
    storageBucket: 'business-management-app-112ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbn2fDWXpGQefpHfsP2-3YGnr--Q1nlps',
    appId: '1:158624427242:ios:d5f11a7e2fd9f7675a3b93',
    messagingSenderId: '158624427242',
    projectId: 'business-management-app-112ea',
    storageBucket: 'business-management-app-112ea.firebasestorage.app',
    iosBundleId: 'com.example.businessManagmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbn2fDWXpGQefpHfsP2-3YGnr--Q1nlps',
    appId: '1:158624427242:ios:d5f11a7e2fd9f7675a3b93',
    messagingSenderId: '158624427242',
    projectId: 'business-management-app-112ea',
    storageBucket: 'business-management-app-112ea.firebasestorage.app',
    iosBundleId: 'com.example.businessManagmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3YqnUEnRfts82fhjOleVPmKMvp3r74pY',
    appId: '1:158624427242:web:e55770443f2dac1d5a3b93',
    messagingSenderId: '158624427242',
    projectId: 'business-management-app-112ea',
    authDomain: 'business-management-app-112ea.firebaseapp.com',
    storageBucket: 'business-management-app-112ea.firebasestorage.app',
    measurementId: 'G-BY19J8L63J',
  );
}
